### ISSUE TITLE
GitHub importer doesn't index snippets correctly (in elasticsearch)

### ISSUE THREAD

**Issue by Lanzafame** [rawcodeio/Bug-Report#1]
So I connected Github to my account and it imported my gists. When I went to view them it presented a 404 and this error:

```
/home/vr10172/rawcode/views/index.ejs:28 26| <h2><%= el.name %></h2> 27| <p> >> 28| <%= el.info.split(/\s+/,10).join(" "); %> ... 29| </p> 30| </a> 31| </div> Cannot call method 'split' of null
```

I am running Version 45.0.2454.101 (64-bit) of Chrome on Mac OS X Yosemite.

**Comment by Lanzafame** [comment]
Issue is present on Chrome 46.0.2490.71 (64-bit) as well.

**Comment by LordLambda** [comment]
Sounds like it could be related to [THIS][issue]? Which was fixed, is this still happening for you?

[issue]:https://github.com/rawcodeio/Bug-Report/issues/2

**Comment by BenMann** [comment]
Partly fixed. The Importer however doesn't properly match the snippets to the respective user ID, which is strange. Will look into it as soon as possible!

**Comment by Lanzafame** [comment]
So I am no longer getting the initial error message. But as @BenMann has pointed out the importer isn't working properly. On my end that presents itself by showing the imported snippets when I initially load the page but if I switch to 'list' view and then switch back to 'snippet' view none of the snippets are displayed. Same disappearance act occurs with switching between 'public' and 'private'.

**Comment by BenMann** [comment]
Oh boy. This is related to a slightly different (older) version of elasticsearch running on the live system. It won't allow mappings starting with an underscore.. such as "_id". This is the reason snippets are not matched to their actual owner - and why it's working in the dev environment.   
Will have to take the risk and update this on the server :-/ 
Of course this requires completely stopping elasticsearch.. fun times!
Will try to do this in a low-traffic-period.

**Comment by BenMann** [comment]
Contrary to what I first thought, the database version was not the main problem. Indexing into elasticsearch didn't work properly, as it was nested incorrectly. The import works for now and consecusive imports will overwrite the existing snippets as wanted. However if an imprted snippet is deleted and then the importer is used again, the deleted snippet will not be properly updated.  

This is mainly due to this: https://github.com/Automattic/mongoose/issues/964 

which might have got fixed three days ago. Will have to update mongoose to see if a deletion correctly triggers an update in elasticsearch. Alternatively call an update on the relevant document in elascticsearch separately.

**Comment by BenMann** [comment]
Bump @Lanzafame @LordLambda

**Comment by Lanzafame** [comment]
@BenMann It does seem to be working but there is some other issues with resulting snippets but I will create a separate issue.

**Comment by BenMann** [comment]
Alright! https://github.com/rawcodeio/Bug-Report/issues/14 is also fixed. Closed for now. :-)
Thanks!
