### ISSUE TITLE
List name text is blank on Lists page

### ISSUE THREAD

**Issue by Lanzafame** [rawcodeio/Bug-Report#14]
![screen shot 2015-10-29 at 8 52 46 am](https://cloud.githubusercontent.com/assets/5924712/10805671/3a1d2e22-7e1b-11e5-86dc-cef29229a657.png)

Clicking on one of the blank lists results in a `ERR_TOO_MANY_REDIRECTS` in Google Chrome Version 46.0.2490.80 (64-bit).

The lists in question were generated from Github Gists import (see #1).

**Comment by Lanzafame** [comment]
I should note that clicking on any of the correctly labelled lists produces the expected result.

**Comment by BenMann** [comment]
Thanks for reporting! 
I already handled this issue by enforcing names on lists. This was not(!) the case some day ago, so lists could fly into the database without a name, giving this redirect error due to how routing works internally. It was handled in: https://github.com/rawcodeio/Bug-Report/issues/7 

However I was also able to fix the already broken lists! 
In case no name was supplied during creation they will now redirect to something like: ```http://rawcode.io/lists/NJ5UE1gZe/noname``` 

That way when lists get the edit-feature, users can "repair" them with a proper name.
Luckily this was not an issue for imported snippets only but rather concerned all snippets. That also means the importer-issue gets a close for now. 

Thanks a ton for testing & telling me ❤️
